# Generated by Django 3.2.7 on 2021-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shoplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(default=13, max_length=16),
            preserve_default=False,
        ),
    ]
