# Generated by Django 3.2.7 on 2021-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=6),
            preserve_default=False,
        ),
    ]
