# Generated by Django 3.2.7 on 2021-10-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopList',
        ),
    ]
