# Generated by Django 3.2.7 on 2021-10-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180702_2213'),
        ('products', '0005_alter_product_featured'),
    ]

    operations = [
    ]
